//Given an android smart phone keypad, input is a number and you
//have to print all possible names(strings) generated by the keypad using given
//number

#include<iostream>
using namespace std;

char keypad[][10] = {"", "", "ABC", "DEF", "GHI", "JKL", "MNO", "PQRS", "TUV", "WXYZ"};

void print_keypad_strings(char*in, char*out, int i, int j){
    if(in[i]=='\0'){
        out[j] = '\0';
        cout<<out<<endl;
        return;
    }

    int digit = in[i] - '0';
    if(digit==1)
        print_keypad_strings(in, out, i+1, j);

    for(int kp = 0; keypad[digit][kp]!='\0'; kp++){
        out[j] = keypad[digit][kp];
        print_keypad_strings(in, out, i+1, j+1);
    }
    return;
}


int main(){
    char in[100];
    cin>>in;
    char out[100];

    print_keypad_strings(in, out, 0, 0);
    return 0;
}
